name: dawarich
description: "Dawarich mobile companion app"
publish_to: 'none'

version: 0.17.2+6

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  android_intent_plus: ^6.0.0
  auto_route: ^11.1.0
  battery_plus: ^7.0.0
  connectivity_plus: ^7.0.0
  country: ^6.0.3
  dawarich_android_user_module:
    git:
      url: https://github.com/sunstep/dawarich-android-user-module
      ref: main
  device_info_plus: ^12.3.0
  device_region: ^1.4.0
  dio: ^5.9.1
  drift: ^2.31.0
  fl_chart: ^1.1.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^20.1.0
  flutter_map: ^8.2.2
  flutter_map_animations: ^0.9.0
  flutter_map_location_marker: ^10.2.0
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  flutter_zxing: ^2.2.1
  freezed_annotation: ^3.1.0

  geolocator: ^14.0.2

  intl: ^0.20.2
  json_annotation: ^4.10.0
  latlong2: ^0.9.1
  network_info_plus: ^7.0.0
  option_result: ^3.2.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sqlcipher_flutter_libs: ^0.6.8
  sqlite3: ^2.9.0
  uuid: ^4.5.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true